version: '3.1'

services:
  web:
    image: task_manager:1.0
    build: .
    ports:
      - "3010:3010"
    environment:  
      - NODE_ENV=production
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo
